[package]
name = "empress"
version = "1.6.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]
edition = "2021"
description = "A D-Bus MPRIS daemon for controlling media players."
documentation = "https://docs.rs/empress"
readme = "README.md"
repository = "https://github.com/ray-kast/empress"
license = "AGPL-3.0-or-later"
keywords = ["mpris", "music", "play", "pause", "skip"]
categories = ["command-line-utilities", "multimedia", "os"]

build = "build.rs"

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
anyhow = "1.0.64"
async-trait = "0.1.57"
atty = "0.2.14"
clap = { version = "3.2.20", features = ["derive"] }
env_logger = "0.9.0"
futures-util = "0.3.24"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.1"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.34"
zbus = { version = "3.1.0", default-features = false, features = ["tokio"] }

[dependencies.tokio]
version = "1.21.0"
features = [
  "macros",
  "net",
  "parking_lot",
  "rt",
  "signal",
  "sync",
  "time",
]

[build-dependencies]
lalrpop = "0.19.8"
