[package]
name = "empress"
version = "0.0.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]
edition = "2018"
description = "A D-Bus MPRIS daemon for controlling media players."
documentation = "https://docs.rs/empress"
repository = "https://github.com/ray-kast/empress"
license = "AGPL-3.0-or-later"
keywords = ["mpris", "music", "play", "pause", "skip"]
categories = ["command-line-utilities", "multimedia", "os"]

[dependencies]
anyhow = "1.0.38"
dbus = "0.9.2"
dbus-tokio = "0.7.3"
structopt = "0.3.21"
tokio = { version = "1.2.0", features = ["macros", "rt", "signal", "sync"] }
