[package]
name = "empress"
version = "1.4.2"
authors = ["rookie1024 <rookie1286@gmail.com>"]
edition = "2021"
description = "A D-Bus MPRIS daemon for controlling media players."
documentation = "https://docs.rs/empress"
readme = "README.md"
repository = "https://github.com/ray-kast/empress"
license = "AGPL-3.0-or-later"
keywords = ["mpris", "music", "play", "pause", "skip"]
categories = ["command-line-utilities", "multimedia", "os"]

[dependencies]
anyhow = "1.0.55"
atty = "0.2.14"
clap = { version = "3.1.2", features = ["derive"] }
dbus = "0.9.5"
dbus-crossroads = "0.5.0"
dbus-tokio = "0.7.5"
env_logger = "0.9.0"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = { version = "0.24.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt", "signal", "sync"] }
