[package]
name = "xtask-build-man"
authors.workspace = true
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.features = ["derive", "string"]
clap.workspace = true
clap_mangen = "0.2.28"
flate2 = "1.1.2"

[lints]
workspace = true
